WebAppHotelManagement/Controllers/BookingController.cs
        using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppHotelManagement.Models;
using WebAppHotelManagement.ViewModels;

namespace WebAppHotelManagement.Controllers
{
    public class BookingController : Controller
    {
        private HotelDBEntities objHotelDbEntities;

        public BookingController()
        {
            objHotelDbEntities = new HotelDBEntities();
        }

        public ActionResult Index()
        {
            BookingViewModel objBookingViewModel = new BookingViewModel();
            objBookingViewModel.ListOfRooms = (from objRoom in objHotelDbEntities.Rooms
                                               where objRoom.BookingStatusId == 2
                                               select new SelectListItem()
                                               {
                                                   Text = objRoom.RoomNumber,
                                                   Value = objRoom.RoomId.ToString()
                                               }
                                             ).ToList();
            objBookingViewModel.BookingFrom = DateTime.Now;
            objBookingViewModel.BookingTo = DateTime.Now.AddDays(1);
            return View(objBookingViewModel);
        }

        [HttpPost]
        public ActionResult Index(BookingViewModel objBookingViewModel  )
        {
            int numberOfDays = Convert.ToInt32((objBookingViewModel.BookingTo - objBookingViewModel.BookingFrom).TotalDays);
            Room objRoom = objHotelDbEntities.Rooms.Single(model => model.RoomId == objBookingViewModel.AssignRoomId);
            decimal RoomPrice = objRoom.RoomPrice;
            decimal TotalAmount = RoomPrice * numberOfDays;

            RoomBooking roomBooking = new RoomBooking()
            {
                BookingFrom = objBookingViewModel.BookingFrom,
                BookingTo = objBookingViewModel.BookingTo,
                AssignRoomId = objBookingViewModel.AssignRoomId,
                CustomerAddress = objBookingViewModel.CustomerAdress,
                CustomerName = objBookingViewModel.CustomerName,
                CustomerPhone = objBookingViewModel.CustomerPhone,
                NoOfMembers = objBookingViewModel.NumberOfMembers,
                TotalAmount = TotalAmount
            };
            objHotelDbEntities.RoomBookings.Add(roomBooking);
            objHotelDbEntities.SaveChanges();

            objRoom.BookingStatusId = 3;
            objHotelDbEntities.SaveChanges();
            return Json(new { message = "Бронювання готелів успішно створено.", success = true }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public PartialViewResult GetAllBookingHistory()
        {
            List<RoomBookingViewModel> listOfBookingViewModels = new List<RoomBookingViewModel>();
            listOfBookingViewModels = (from objHotelBooking in objHotelDbEntities.RoomBookings
                                       join objRoom in objHotelDbEntities.Rooms on objHotelBooking.AssignRoomId equals objRoom.RoomId
                                       select new RoomBookingViewModel() {
                                           BookingFrom = objHotelBooking.BookingFrom,
                                           BookingTo = objHotelBooking.BookingTo,
                                           CustomerPhone = objHotelBooking.CustomerPhone,
                                           CustomerName = objHotelBooking.CustomerName,
                                           TotalAmount = objHotelBooking.TotalAmount,
                                           CustomerAdress = objHotelBooking.CustomerAddress,
                                           NumberOfMembers = objHotelBooking.NoOfMembers,
                                           BookingId = objHotelBooking.BookingId,
                                           RoomNumber = objRoom.RoomNumber,
                                           RoomPrice = objRoom.RoomPrice,
                                           NumberOfDays = System.Data.Entity.DbFunctions.DiffDays(objHotelBooking.BookingFrom, objHotelBooking.BookingTo).Value 
                                           
                                       }).ToList();
            return PartialView("_BookingHistoryPartial", listOfBookingViewModels);
        }     

    }
}

WebAppHotelManagement/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppHotelManagement.Models;
using WebAppHotelManagement.ViewModels;

namespace WebAppHotelManagement.Controllers
{
    public class RoomController : Controller
    {
        private HotelDBEntities objHotelDbEntities;
        public RoomController()
        {
            objHotelDbEntities = new HotelDBEntities();
        }
        // GET: Room
        public ActionResult Index()
        {
            RoomViewModel objRoomViewModel = new RoomViewModel();
            objRoomViewModel.ListOfBookingStatus = (from obj in objHotelDbEntities.BookingStatus
                                                    select new SelectListItem()
                                                    {
                                                        Text=obj.BookingStatus,
                                                        Value=obj.BookingStatusId.ToString()
                                                    }).ToList();

            objRoomViewModel.ListOfRoomType = (from obj in objHotelDbEntities.RoomTypes
                                              select new SelectListItem()
                                              {
                                                  Text = obj.RoomTypeName,
                                                  Value = obj.RoomTypeId.ToString()
                                              }).ToList();
            return View(objRoomViewModel);
        }
        [HttpPost]
        public ActionResult Index(RoomViewModel objRoomViewModel)
        {
            string message = String.Empty;
            string ImageUniqueName = String.Empty;
            string ActualImageName = String.Empty;

            if (objRoomViewModel.RoomId == 0)
            {
                ImageUniqueName = Guid.NewGuid().ToString();
                ActualImageName = ImageUniqueName + Path.GetExtension(objRoomViewModel.Image.FileName);
                objRoomViewModel.Image.SaveAs(Server.MapPath("~/RoomImages/" + ActualImageName));
                //objHotelDbEntities
                Room objRoom = new Room()
                {
                    RoomNumber = objRoomViewModel.RoomNumber,
                    RoomDescription = objRoomViewModel.RoomDescription,
                    RoomPrice = objRoomViewModel.RoomPrice,
                    BookingStatusId = objRoomViewModel.BookingStatusId,
                    IsActive = true,
                    RoomImage = ActualImageName,
                    RoomCapacity = objRoomViewModel.RoomCapacity,
                    RoomTypeId = objRoomViewModel.RoomTypeId
                };
                objHotelDbEntities.Rooms.Add(objRoom);
                message = "додана.";
            }
            else
            {
                Room objRoom = objHotelDbEntities.Rooms.Single(model => model.RoomId == objRoomViewModel.RoomId);
                if (objRoomViewModel.Image != null)
                {
                    ImageUniqueName = Guid.NewGuid().ToString();
                    ActualImageName = ImageUniqueName + Path.GetExtension(objRoomViewModel.Image.FileName);
                    objRoomViewModel.Image.SaveAs(Server.MapPath("~/RoomImages/" + ActualImageName));
                    objRoom.RoomImage = ActualImageName;
                }

                objRoom.RoomNumber = objRoomViewModel.RoomNumber;
                objRoom.RoomDescription = objRoomViewModel.RoomDescription;
                objRoom.RoomPrice = objRoomViewModel.RoomPrice;
                objRoom.BookingStatusId = objRoomViewModel.BookingStatusId;
                objRoom.IsActive = true;
                objRoom.RoomCapacity = objRoomViewModel.RoomCapacity;
                objRoom.RoomTypeId = objRoomViewModel.RoomTypeId;
                message = "Оновлено.";
            }
            
            objHotelDbEntities.SaveChanges();

            return Json(new {message= "Кімната успішно " + message, success = true }, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult GetAllRooms()
        {
            IEnumerable<RoomDetailsViewModel> listOfRoomDetailsViewModels =
                (from objRoom in objHotelDbEntities.Rooms
                 join objBooking in objHotelDbEntities.BookingStatus on objRoom.BookingStatusId equals objBooking.BookingStatusId
                 join objRoomType in objHotelDbEntities.RoomTypes on objRoom.RoomTypeId equals objRoomType.RoomTypeId
                 where objRoom.IsActive == true
                 select new RoomDetailsViewModel()
                 {
                     RoomNumber = objRoom.RoomNumber,
                     RoomDescription = objRoom.RoomDescription,
                     RoomCapacity = objRoom.RoomCapacity,
                     RoomPrice = objRoom.RoomPrice,
                     BookingStatus = objBooking.BookingStatus,
                     RoomType = objRoomType.RoomTypeName,
                     RoomImage = objRoom.RoomImage,
                     RoomId = objRoom.RoomId
                 }).ToList();
            return PartialView("_RoomDetailsPartial", listOfRoomDetailsViewModels);
        }

        [HttpGet]
        public JsonResult EditRoomDetails(int roomId)
        {
            var result = objHotelDbEntities.Rooms.Single(model => model.RoomId == roomId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult DeleteRoomDetails(int roomId)
        {
            Room objRoom = objHotelDbEntities.Rooms.Single(model => model.RoomId == roomId);
            objRoom.IsActive = false;
            objHotelDbEntities.SaveChanges();
            return Json(new { message = "Запис успішно видалено.", success = true }, JsonRequestBehavior.AllowGet);
        }

    }
}

WebAppHotelManagement/Views/Shared/_BookingHistoryPartial.cshtml
@model IEnumerable<WebAppHotelManagement.ViewModels.RoomBookingViewModel>

<style type="text/css">
    TABLE {
        width: 300px; /* Ширина таблицы */
        border: 1px solid silver; /* Рамка вокруг таблицы */
        border-bottom: none; /* Убираем линию снизу */
    }

    TD, TH {
        padding: 3px; /* Поля вокруг содержимого ячеек */
        border: 1px solid silver; /* Рамка вокруг таблицы */
    }

    TH {
        text-align: left; /* Выравнивание по левому краю */


    }

    TD {
        border-bottom: 1px solid silver; /* Линия снизу */
    }
</style>

<table class="table table-sm" style="width: 100%">
    <thead>
        <tr class="bg-primary" style="color: white;">
            <th>
                Ім'я
            </th>
            <th>
                Адреса
            </th>
            <th>
                Номер
            </th>
            <th>
                Початок брон.
            </th>
            <th>
                Кiнець брон.
            </th>
            <th>
                Кімната
            </th>
            <th>
                Кількість проживаючих
            </th>
            <th>
                Кiлькiсть днiв
            </th>
            <th>
                Вартість Номера(грн.)
            </th>
            <th>
                Загальна вартiсть(грн.)
            </th>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.CustomerName
                </td>
                <td>
                    @item.CustomerAdress
                </td>
                <td>
                    @item.CustomerPhone
                </td>
                <td>
                    @item.BookingFrom.ToString("dd-MMM-yyyy")
                </td>
                <td>
                    @item.BookingTo.ToString("dd-MMM-yyyy")
                </td>
                <td>
                    @item.RoomNumber
                </td>
                <td>
                    @item.NumberOfMembers
                </td>
                <td>
                    @item.NumberOfDays
                </td>
                <td>
                    @item.RoomPrice.ToString("#,##0.00")
                </td>
                <td>
                    @item.TotalAmount.ToString("#,##0.00")
                </td>

            </tr>
        }
    </tbody>
</table>

WebAppHotelManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Готельний менеджмент</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<style>
    html {
        overflow: scroll;
    }


    header[role="banner"] #logo-main {
        display: block;
        margin: 20px auto;
    }

    #navbar-primary.navbar-default {
        background: transparent;
        border: none;
    }

        #navbar-primary.navbar-default .navbar-nav {
            width: 100%;
            text-align: center;
        }

            #navbar-primary.navbar-default .navbar-nav > li {
                display: inline-block;
                float: none;
            }

                #navbar-primary.navbar-default .navbar-nav > li > a {
                    padding-left: 30px;
                    padding-right: 30px;
                }
</style>


<header role="banner" style="width: 100%">
    <img id="logo-main" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/32877/logo-thing.png" width="200" alt="Logo Thing main logo">
    <nav id="navbar-primary" class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-primary-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navbar-primary-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">@Html.ActionLink("Головна", "Index", "Home")</li>
                    <li class="active">@Html.ActionLink("Контакти", "Contact", "Home")</li>
                    <li class="active">@Html.ActionLink("Апартаменти", "Index", "Room")</li>
                    <li class="active">@Html.ActionLink("Бронювання", "Index", "Booking")</li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</header><!-- header role="banner" -->




    <div class="container body-content mt-lg-3">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Готельний менеджмент</p>
        </footer>
    </div>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/additional-methods.min.js"></script>
</body>
</html>

WebAppHotelManagement/Views/Shared/_RoomDetailsPartial.cshtml
@model IEnumerable<WebAppHotelManagement.ViewModels.RoomDetailsViewModel>

<table class="table table-sm" style="width: 100%">
    <thead>
        <tr class="bg-primary" style="color: white;">
            <th>
                Дія
            </th>
            <th>
                Зображення
            </th>
            <th>
                Номер кімнати
            </th>
            <th>
                Ціна номера
            </th>
            <th>
                Статус бронювання
            </th>
            <th>
                Тип номера
            </th>
            <th>
                Місткість номера
            </th>
            <th>
                Опис номера
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
        <tr>
            <td>
                <span id="btnDelete" class="glyphicon glyphicon-trash" onclick="DeleteRoom(@item.RoomId)"></span> &nbsp;&nbsp;
                <span id="btnEdit" class="glyphicon glyphicon-pencil" onclick="EditRoom(@item.RoomId)"></span>
            </td>
            <td>
                <img src="@Url.Content("~/RoomImages/" + item.RoomImage)" width="50" height="50" class="img-responsive" />
            </td>
            <td>
                @item.RoomNumber
            </td>
            <td>
                @item.RoomPrice
            </td>
            <td>
                @item.BookingStatus
            </td>
            <td>
                @item.RoomType
            </td>
            <td>
                @item.RoomCapacity
            </td>
            <td>
                @item.RoomDescription
            </td>
        </tr>
        }
    </tbody>
</table>